### ISSUE TITLE
Use jll?

### ISSUE THREAD

**Issue by aviks** [kdheepak/Pandoc.jl#13]
This package should presumably use the [Pandoc JLL package](https://github.com/juliabinaryWrappers/pandoc_jll.jl), so that the end user does not need to separately install the pandoc binaries?

**Comment by kdheepak** [comment]
I agree!

fyi I’m on travel and won’t be able to make any changes for possibly a few weeks.

**Comment by aviks** [comment]
Thanks. I'm in no hurry, just came across this package and thought I'd mention it.

**Comment by kdheepak** [comment]
Resolved on this version https://github.com/kdheepak/Pandoc.jl/releases/tag/v0.3.0
