### ISSUE TITLE
InlineMath problems for `Document` types

### ISSUE THREAD

**Issue by iagobaapellaniz** [kdheepak/Pandoc.jl#17]
I found the following issue

When converting from `.md` to `.json` with the `Converter` the output looks something like
```
... "Space"},{"t":"Math","c":[{"t":"InlineMath"},"P(a,b)"]},{"t":"Str" ...
```

But when reading it with `Document` and then later converting it to json with `JSON3.write`, it looks something like
```
... "Space"},{"t":"Math","c":["InlineMath","P(a,b)"]},{"t":"Str" ...
```

Note the missing object which is now a string.

**Comment by kdheepak** [comment]
Thanks for reporting! I’ll have to look into this over the weekend.
